# af-server/cloudbuild.yaml
# Cloud Build CI/CD pipeline for AF Server V2
# Mirrors the pattern used in af-platform/cloudbuild.yaml
#
# Trigger: push to main branch (configure in GCP Console > Cloud Build > Triggers)
# Region: asia-northeast1 (Tokyo — matches Datastore)
# Service name: af-server

steps:
  # 1. Build container image
  - name: "gcr.io/cloud-builders/docker"
    dir: "af-server"
    args:
      - "build"
      - "-t"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/af-server/af-server:$COMMIT_SHA"
      - "-t"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/af-server/af-server:latest"
      - "."

  # 2. Push to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/af-server/af-server"

  # 3. Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "af-server"
      - "--image"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/af-server/af-server:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"       # Auth handled inside the app via Firebase tokens
      - "--service-account"
      - "af-server@$PROJECT_ID.iam.gserviceaccount.com"
      - "--add-cloudsql-instances"
      - "cloud-accele-freight:asia-northeast1:af-db"
      - "--set-secrets"
      - "DATABASE_URL=DATABASE_URL:latest,DB_USER=DB_USER:latest,DB_PASS=DB_PASS:latest,INSTANCE_CONNECTION_NAME=INSTANCE_CONNECTION_NAME:latest"
      - "--set-env-vars"
      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID"

images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/af-server/af-server:$COMMIT_SHA"
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/af-server/af-server:latest"

timeout: "1200s"
