-- Migration 006: Countries table with full global seed data
-- Run against the accelefreight database.
-- Currency rules:
--   MY  -> MYR, AU -> AUD, SG -> SGD, EU members -> EUR, all others -> USD
-- Tax pre-populated for MY (SST, rate TBD) and SG (GST, 9%) only.

CREATE TABLE IF NOT EXISTS countries (
    country_code     VARCHAR(2)    PRIMARY KEY,  -- ISO 3166-1 alpha-2
    name             VARCHAR(100)  NOT NULL,
    currency_code    VARCHAR(3),                 -- ISO 4217
    currency_symbol  VARCHAR(10),
    tax_label        VARCHAR(20),                -- e.g. GST, SST, VAT
    tax_rate         NUMERIC(5,2)  NULL,         -- percent, e.g. 9.00
    tax_applicable   BOOLEAN       NOT NULL DEFAULT FALSE,
    is_active        BOOLEAN       NOT NULL DEFAULT TRUE
);

-- =========================================================================
-- Seed: Full global country list
-- Format: (country_code, name, currency_code, currency_symbol, tax_label, tax_rate, tax_applicable)
-- =========================================================================

INSERT INTO countries (country_code, name, currency_code, currency_symbol, tax_label, tax_rate, tax_applicable) VALUES

-- Malaysia
('MY', 'Malaysia',                          'MYR', 'RM',   'SST',  6.00, TRUE),

-- Singapore
('SG', 'Singapore',                         'SGD', 'S$',   'GST',  9.00, TRUE),

-- Australia
('AU', 'Australia',                         'AUD', 'A$',   NULL,   NULL, FALSE),

-- EU Members (EUR)
('AT', 'Austria',                           'EUR', '€',    'VAT',  NULL, FALSE),
('BE', 'Belgium',                           'EUR', '€',    'VAT',  NULL, FALSE),
('BG', 'Bulgaria',                          'EUR', '€',    'VAT',  NULL, FALSE),
('CY', 'Cyprus',                            'EUR', '€',    'VAT',  NULL, FALSE),
('CZ', 'Czech Republic',                    'EUR', '€',    'VAT',  NULL, FALSE),
('DE', 'Germany',                           'EUR', '€',    'VAT',  NULL, FALSE),
('DK', 'Denmark',                           'EUR', '€',    'VAT',  NULL, FALSE),
('EE', 'Estonia',                           'EUR', '€',    'VAT',  NULL, FALSE),
('ES', 'Spain',                             'EUR', '€',    'VAT',  NULL, FALSE),
('FI', 'Finland',                           'EUR', '€',    'VAT',  NULL, FALSE),
('FR', 'France',                            'EUR', '€',    'VAT',  NULL, FALSE),
('GR', 'Greece',                            'EUR', '€',    'VAT',  NULL, FALSE),
('HR', 'Croatia',                           'EUR', '€',    'VAT',  NULL, FALSE),
('HU', 'Hungary',                           'EUR', '€',    'VAT',  NULL, FALSE),
('IE', 'Ireland',                           'EUR', '€',    'VAT',  NULL, FALSE),
('IT', 'Italy',                             'EUR', '€',    'VAT',  NULL, FALSE),
('LT', 'Lithuania',                         'EUR', '€',    'VAT',  NULL, FALSE),
('LU', 'Luxembourg',                        'EUR', '€',    'VAT',  NULL, FALSE),
('LV', 'Latvia',                            'EUR', '€',    'VAT',  NULL, FALSE),
('MT', 'Malta',                             'EUR', '€',    'VAT',  NULL, FALSE),
('NL', 'Netherlands',                       'EUR', '€',    'VAT',  NULL, FALSE),
('PL', 'Poland',                            'EUR', '€',    'VAT',  NULL, FALSE),
('PT', 'Portugal',                          'EUR', '€',    'VAT',  NULL, FALSE),
('RO', 'Romania',                           'EUR', '€',    'VAT',  NULL, FALSE),
('SE', 'Sweden',                            'EUR', '€',    'VAT',  NULL, FALSE),
('SI', 'Slovenia',                          'EUR', '€',    'VAT',  NULL, FALSE),
('SK', 'Slovakia',                          'EUR', '€',    'VAT',  NULL, FALSE),

-- Rest of world (USD) — major trading partners first, then full global list
('US', 'United States',                     'USD', '$',    NULL,   NULL, FALSE),
('CN', 'China',                             'USD', '$',    NULL,   NULL, FALSE),
('JP', 'Japan',                             'USD', '$',    NULL,   NULL, FALSE),
('KR', 'South Korea',                       'USD', '$',    NULL,   NULL, FALSE),
('IN', 'India',                             'USD', '$',    NULL,   NULL, FALSE),
('GB', 'United Kingdom',                    'USD', '$',    NULL,   NULL, FALSE),
('HK', 'Hong Kong',                         'USD', '$',    NULL,   NULL, FALSE),
('TW', 'Taiwan',                            'USD', '$',    NULL,   NULL, FALSE),
('TH', 'Thailand',                          'USD', '$',    NULL,   NULL, FALSE),
('ID', 'Indonesia',                         'USD', '$',    NULL,   NULL, FALSE),
('VN', 'Vietnam',                           'USD', '$',    NULL,   NULL, FALSE),
('PH', 'Philippines',                       'USD', '$',    NULL,   NULL, FALSE),
('BD', 'Bangladesh',                        'USD', '$',    NULL,   NULL, FALSE),
('PK', 'Pakistan',                          'USD', '$',    NULL,   NULL, FALSE),
('LK', 'Sri Lanka',                         'USD', '$',    NULL,   NULL, FALSE),
('MM', 'Myanmar',                           'USD', '$',    NULL,   NULL, FALSE),
('KH', 'Cambodia',                          'USD', '$',    NULL,   NULL, FALSE),
('LA', 'Laos',                              'USD', '$',    NULL,   NULL, FALSE),
('BN', 'Brunei',                            'USD', '$',    NULL,   NULL, FALSE),
('MO', 'Macau',                             'USD', '$',    NULL,   NULL, FALSE),
('MN', 'Mongolia',                          'USD', '$',    NULL,   NULL, FALSE),
('NP', 'Nepal',                             'USD', '$',    NULL,   NULL, FALSE),
('AF', 'Afghanistan',                       'USD', '$',    NULL,   NULL, FALSE),
('CA', 'Canada',                            'USD', '$',    NULL,   NULL, FALSE),
('MX', 'Mexico',                            'USD', '$',    NULL,   NULL, FALSE),
('BR', 'Brazil',                            'USD', '$',    NULL,   NULL, FALSE),
('AR', 'Argentina',                         'USD', '$',    NULL,   NULL, FALSE),
('CL', 'Chile',                             'USD', '$',    NULL,   NULL, FALSE),
('CO', 'Colombia',                          'USD', '$',    NULL,   NULL, FALSE),
('PE', 'Peru',                              'USD', '$',    NULL,   NULL, FALSE),
('VE', 'Venezuela',                         'USD', '$',    NULL,   NULL, FALSE),
('EC', 'Ecuador',                           'USD', '$',    NULL,   NULL, FALSE),
('UY', 'Uruguay',                           'USD', '$',    NULL,   NULL, FALSE),
('BO', 'Bolivia',                           'USD', '$',    NULL,   NULL, FALSE),
('PY', 'Paraguay',                          'USD', '$',    NULL,   NULL, FALSE),
('NZ', 'New Zealand',                       'USD', '$',    NULL,   NULL, FALSE),
('FJ', 'Fiji',                              'USD', '$',    NULL,   NULL, FALSE),
('PG', 'Papua New Guinea',                  'USD', '$',    NULL,   NULL, FALSE),
('ZA', 'South Africa',                      'USD', '$',    NULL,   NULL, FALSE),
('NG', 'Nigeria',                           'USD', '$',    NULL,   NULL, FALSE),
('EG', 'Egypt',                             'USD', '$',    NULL,   NULL, FALSE),
('KE', 'Kenya',                             'USD', '$',    NULL,   NULL, FALSE),
('ET', 'Ethiopia',                          'USD', '$',    NULL,   NULL, FALSE),
('GH', 'Ghana',                             'USD', '$',    NULL,   NULL, FALSE),
('TZ', 'Tanzania',                          'USD', '$',    NULL,   NULL, FALSE),
('UG', 'Uganda',                            'USD', '$',    NULL,   NULL, FALSE),
('DZ', 'Algeria',                           'USD', '$',    NULL,   NULL, FALSE),
('MA', 'Morocco',                           'USD', '$',    NULL,   NULL, FALSE),
('TN', 'Tunisia',                           'USD', '$',    NULL,   NULL, FALSE),
('LY', 'Libya',                             'USD', '$',    NULL,   NULL, FALSE),
('SD', 'Sudan',                             'USD', '$',    NULL,   NULL, FALSE),
('AO', 'Angola',                            'USD', '$',    NULL,   NULL, FALSE),
('MZ', 'Mozambique',                        'USD', '$',    NULL,   NULL, FALSE),
('ZM', 'Zambia',                            'USD', '$',    NULL,   NULL, FALSE),
('ZW', 'Zimbabwe',                          'USD', '$',    NULL,   NULL, FALSE),
('CM', 'Cameroon',                          'USD', '$',    NULL,   NULL, FALSE),
('CI', 'Ivory Coast',                       'USD', '$',    NULL,   NULL, FALSE),
('SN', 'Senegal',                           'USD', '$',    NULL,   NULL, FALSE),
('MG', 'Madagascar',                        'USD', '$',    NULL,   NULL, FALSE),
('SA', 'Saudi Arabia',                      'USD', '$',    NULL,   NULL, FALSE),
('AE', 'United Arab Emirates',              'USD', '$',    NULL,   NULL, FALSE),
('IQ', 'Iraq',                              'USD', '$',    NULL,   NULL, FALSE),
('IR', 'Iran',                              'USD', '$',    NULL,   NULL, FALSE),
('IL', 'Israel',                            'USD', '$',    NULL,   NULL, FALSE),
('JO', 'Jordan',                            'USD', '$',    NULL,   NULL, FALSE),
('LB', 'Lebanon',                           'USD', '$',    NULL,   NULL, FALSE),
('KW', 'Kuwait',                            'USD', '$',    NULL,   NULL, FALSE),
('QA', 'Qatar',                             'USD', '$',    NULL,   NULL, FALSE),
('BH', 'Bahrain',                           'USD', '$',    NULL,   NULL, FALSE),
('OM', 'Oman',                              'USD', '$',    NULL,   NULL, FALSE),
('YE', 'Yemen',                             'USD', '$',    NULL,   NULL, FALSE),
('SY', 'Syria',                             'USD', '$',    NULL,   NULL, FALSE),
('TR', 'Turkey',                            'USD', '$',    NULL,   NULL, FALSE),
('RU', 'Russia',                            'USD', '$',    NULL,   NULL, FALSE),
('UA', 'Ukraine',                           'USD', '$',    NULL,   NULL, FALSE),
('KZ', 'Kazakhstan',                        'USD', '$',    NULL,   NULL, FALSE),
('UZ', 'Uzbekistan',                        'USD', '$',    NULL,   NULL, FALSE),
('AZ', 'Azerbaijan',                        'USD', '$',    NULL,   NULL, FALSE),
('GE', 'Georgia',                           'USD', '$',    NULL,   NULL, FALSE),
('AM', 'Armenia',                           'USD', '$',    NULL,   NULL, FALSE),
('BY', 'Belarus',                           'USD', '$',    NULL,   NULL, FALSE),
('MD', 'Moldova',                           'USD', '$',    NULL,   NULL, FALSE),
('RS', 'Serbia',                            'USD', '$',    NULL,   NULL, FALSE),
('BA', 'Bosnia and Herzegovina',            'USD', '$',    NULL,   NULL, FALSE),
('AL', 'Albania',                           'USD', '$',    NULL,   NULL, FALSE),
('MK', 'North Macedonia',                   'USD', '$',    NULL,   NULL, FALSE),
('ME', 'Montenegro',                        'USD', '$',    NULL,   NULL, FALSE),
('XK', 'Kosovo',                            'USD', '$',    NULL,   NULL, FALSE),
('NO', 'Norway',                            'USD', '$',    NULL,   NULL, FALSE),
('CH', 'Switzerland',                       'USD', '$',    NULL,   NULL, FALSE),
('IS', 'Iceland',                           'USD', '$',    NULL,   NULL, FALSE),
('LI', 'Liechtenstein',                     'USD', '$',    NULL,   NULL, FALSE),
('MC', 'Monaco',                            'USD', '$',    NULL,   NULL, FALSE),
('AD', 'Andorra',                           'USD', '$',    NULL,   NULL, FALSE),
('SM', 'San Marino',                        'USD', '$',    NULL,   NULL, FALSE),
('VA', 'Vatican City',                      'USD', '$',    NULL,   NULL, FALSE),
('PK', 'Pakistan',                          'USD', '$',    NULL,   NULL, FALSE),
('CU', 'Cuba',                              'USD', '$',    NULL,   NULL, FALSE),
('DO', 'Dominican Republic',                'USD', '$',    NULL,   NULL, FALSE),
('GT', 'Guatemala',                         'USD', '$',    NULL,   NULL, FALSE),
('HN', 'Honduras',                          'USD', '$',    NULL,   NULL, FALSE),
('SV', 'El Salvador',                       'USD', '$',    NULL,   NULL, FALSE),
('NI', 'Nicaragua',                         'USD', '$',    NULL,   NULL, FALSE),
('CR', 'Costa Rica',                        'USD', '$',    NULL,   NULL, FALSE),
('PA', 'Panama',                            'USD', '$',    NULL,   NULL, FALSE),
('JM', 'Jamaica',                           'USD', '$',    NULL,   NULL, FALSE),
('TT', 'Trinidad and Tobago',               'USD', '$',    NULL,   NULL, FALSE),
('GY', 'Guyana',                            'USD', '$',    NULL,   NULL, FALSE),
('SR', 'Suriname',                          'USD', '$',    NULL,   NULL, FALSE),
('HT', 'Haiti',                             'USD', '$',    NULL,   NULL, FALSE),
('MW', 'Malawi',                            'USD', '$',    NULL,   NULL, FALSE),
('RW', 'Rwanda',                            'USD', '$',    NULL,   NULL, FALSE),
('BI', 'Burundi',                           'USD', '$',    NULL,   NULL, FALSE),
('SO', 'Somalia',                           'USD', '$',    NULL,   NULL, FALSE),
('DJ', 'Djibouti',                          'USD', '$',    NULL,   NULL, FALSE),
('ER', 'Eritrea',                           'USD', '$',    NULL,   NULL, FALSE),
('SS', 'South Sudan',                       'USD', '$',    NULL,   NULL, FALSE),
('CF', 'Central African Republic',          'USD', '$',    NULL,   NULL, FALSE),
('TD', 'Chad',                              'USD', '$',    NULL,   NULL, FALSE),
('NE', 'Niger',                             'USD', '$',    NULL,   NULL, FALSE),
('ML', 'Mali',                              'USD', '$',    NULL,   NULL, FALSE),
('BF', 'Burkina Faso',                      'USD', '$',    NULL,   NULL, FALSE),
('GN', 'Guinea',                            'USD', '$',    NULL,   NULL, FALSE),
('GW', 'Guinea-Bissau',                     'USD', '$',    NULL,   NULL, FALSE),
('SL', 'Sierra Leone',                      'USD', '$',    NULL,   NULL, FALSE),
('LR', 'Liberia',                           'USD', '$',    NULL,   NULL, FALSE),
('TG', 'Togo',                              'USD', '$',    NULL,   NULL, FALSE),
('BJ', 'Benin',                             'USD', '$',    NULL,   NULL, FALSE),
('GM', 'Gambia',                            'USD', '$',    NULL,   NULL, FALSE),
('CV', 'Cape Verde',                        'USD', '$',    NULL,   NULL, FALSE),
('ST', 'Sao Tome and Principe',             'USD', '$',    NULL,   NULL, FALSE),
('GQ', 'Equatorial Guinea',                 'USD', '$',    NULL,   NULL, FALSE),
('GA', 'Gabon',                             'USD', '$',    NULL,   NULL, FALSE),
('CG', 'Republic of the Congo',             'USD', '$',    NULL,   NULL, FALSE),
('CD', 'Democratic Republic of the Congo',  'USD', '$',    NULL,   NULL, FALSE),
('NA', 'Namibia',                           'USD', '$',    NULL,   NULL, FALSE),
('BW', 'Botswana',                          'USD', '$',    NULL,   NULL, FALSE),
('SZ', 'Eswatini',                          'USD', '$',    NULL,   NULL, FALSE),
('LS', 'Lesotho',                           'USD', '$',    NULL,   NULL, FALSE),
('MU', 'Mauritius',                         'USD', '$',    NULL,   NULL, FALSE),
('SC', 'Seychelles',                        'USD', '$',    NULL,   NULL, FALSE),
('KM', 'Comoros',                           'USD', '$',    NULL,   NULL, FALSE),
('MV', 'Maldives',                          'USD', '$',    NULL,   NULL, FALSE),
('BT', 'Bhutan',                            'USD', '$',    NULL,   NULL, FALSE),
('TL', 'Timor-Leste',                       'USD', '$',    NULL,   NULL, FALSE),
('PW', 'Palau',                             'USD', '$',    NULL,   NULL, FALSE),
('FM', 'Micronesia',                        'USD', '$',    NULL,   NULL, FALSE),
('MH', 'Marshall Islands',                  'USD', '$',    NULL,   NULL, FALSE),
('NR', 'Nauru',                             'USD', '$',    NULL,   NULL, FALSE),
('KI', 'Kiribati',                          'USD', '$',    NULL,   NULL, FALSE),
('TV', 'Tuvalu',                            'USD', '$',    NULL,   NULL, FALSE),
('WS', 'Samoa',                             'USD', '$',    NULL,   NULL, FALSE),
('TO', 'Tonga',                             'USD', '$',    NULL,   NULL, FALSE),
('VU', 'Vanuatu',                           'USD', '$',    NULL,   NULL, FALSE),
('SB', 'Solomon Islands',                   'USD', '$',    NULL,   NULL, FALSE),
('CK', 'Cook Islands',                      'USD', '$',    NULL,   NULL, FALSE),
('NU', 'Niue',                              'USD', '$',    NULL,   NULL, FALSE),
('WF', 'Wallis and Futuna',                 'USD', '$',    NULL,   NULL, FALSE),
('NC', 'New Caledonia',                     'USD', '$',    NULL,   NULL, FALSE),
('PF', 'French Polynesia',                  'USD', '$',    NULL,   NULL, FALSE),
('TK', 'Tokelau',                           'USD', '$',    NULL,   NULL, FALSE),
('AS', 'American Samoa',                    'USD', '$',    NULL,   NULL, FALSE),
('GU', 'Guam',                              'USD', '$',    NULL,   NULL, FALSE),
('MP', 'Northern Mariana Islands',          'USD', '$',    NULL,   NULL, FALSE)

ON CONFLICT (country_code) DO NOTHING;
