-- ============================================================
-- DEPRECATED — Do not run this migration.
-- Superseded by the geography restructure (migration 028+).
-- This file is retained for historical reference only.
-- ============================================================

-- Migration 027: Seed transport areas from legacy PricingTransport Datastore data
-- Generated: 2026-03-10
-- 153 rows across 123 unique city codes
--
-- Run after migration 026 with Cloud SQL Auth Proxy active.

INSERT INTO areas (area_code, area_name, port_un_code, state_code, is_active) VALUES
    ('AE-215', 'Umm Ramool', 'DXB', NULL, true),
    ('AE-DXB-000', 'Dubai', 'AEJEA', NULL, true),
    ('AE-DXB-000', 'Dubai', 'DXB', NULL, true),
    ('AE-DXB-002', 'Dubai Logistics City', 'DXB', NULL, true),
    ('AU-NSW-SYD', 'Sydney Metro', 'SYD', NULL, true),
    ('AU-WA-6069', 'Ellenbrook, WA', 'PER', NULL, true),
    ('BD-1222', 'Mohammadpur', 'BDCGP', NULL, true),
    ('BD-1222', 'Mohammadpur', 'DAC', NULL, true),
    ('BE-AN-2110', 'Wijnegem, Antwerp (2110)', 'BEANR', NULL, true),
    ('BE-AN-2110', 'Wijnegem, Antwerp (2110)', 'NLRTM', NULL, true),
    ('BN-T4', 'Tutong District', 'BWN', NULL, true),
    ('CH-3400', 'Burgdorf', 'CHZRH', NULL, true),
    ('CH-3400', 'Burgdorf', 'ZRH', NULL, true),
    ('CH-ZUR-000', 'Zurich', 'BEANR', NULL, true),
    ('CN-AH-15-0564', 'LU''AN, ANHUI', 'CNSHG', NULL, true),
    ('CN-BJ', 'BEIJING', 'CNTXG', NULL, true),
    ('CN-BJ-10-100020', 'Chaoyang', 'CNTXG', NULL, true),
    ('CN-BJ-10-100020', 'Chaoyang', 'PEK', NULL, true),
    ('CN-BJ-10-10080', 'Haidian District, Beijing', 'PEK', NULL, true),
    ('CN-FJ', 'FUJIAN', 'XMN', NULL, true),
    ('CN-FJ-02-361006', 'Huli District, Xiamen', 'CNXMG', NULL, true),
    ('CN-GD', 'Guangdong', 'CAN', NULL, true),
    ('CN-GD-01-020-440115', 'Nansha District, Guangzhou', 'CNSZX', NULL, true),
    ('CN-GD-01-020-511300', 'Zengcheng District, Guangzhou', 'CNCAN', NULL, true),
    ('CN-GD-01-020-511300', 'Zengcheng District, Guangzhou', 'CNSZX', NULL, true),
    ('CN-GD-01-020-528400', 'ZHONGSAN', 'CNSZX', NULL, true),
    ('CN-GD-03', 'Shenzhen', 'SZX', NULL, true),
    ('CN-GD-06', 'Foshan, Guangdong', 'CNSZX', NULL, true),
    ('CN-GD-13-51600', 'Huizhou City, Guangdong', 'CNSZX', NULL, true),
    ('CN-GDG-003', 'Wanjiang District, Dongguan', 'CNSZX', NULL, true),
    ('CN-GZ-020', 'Huangpu District, Guangzhou', 'CAN', NULL, true),
    ('CN-HB-433000', 'XIANTAO, HUBEI', 'CNSHG', NULL, true),
    ('CN-HE-01-050000', 'Shijiazhuang, HEBEI', 'CNTXG', NULL, true),
    ('CN-JS', 'Jiangsu', 'CNSHG', NULL, true),
    ('CN-JS-0510', 'Yixing City, Jiangsu', 'PVG', NULL, true),
    ('CN-JS-13', 'Suqian, Jiangsu', 'CNSHG', NULL, true),
    ('CN-JS-215000', 'Suzhou, Jiangsu', 'PVG', NULL, true),
    ('CN-LN-01-110000', 'Shenyang, Liaoning', 'PEK', NULL, true),
    ('CN-SC-01', 'Chengdu', 'CNSHG', NULL, true),
    ('CN-SD-02-266500', 'Xihai''an, Qingdao', 'CNQDG', NULL, true),
    ('CN-SH-201100', 'Minhang District, Shanghai', 'CNSHG', NULL, true),
    ('CN-ZH-05', 'Huzhou, Zhejiang', 'CNSHG', NULL, true),
    ('CN-ZJ-02', 'Ningbo City', 'CNNGB', NULL, true),
    ('CN-ZJ-02', 'Ningbo City', 'PVG', NULL, true),
    ('CN-ZJ-02', 'Ningbo City', 'SHA', NULL, true),
    ('CN-ZJ-03-325000', 'Wenzhou City, Zhejiang', 'CNNGB', NULL, true),
    ('CN-ZJ-03-325000', 'Wenzhou City, Zhejiang', 'CNSHG', NULL, true),
    ('DE-24568', 'Kaltenkirchen', 'HAM', NULL, true),
    ('DE-33442', 'Herzebrock-Clarholz', 'BEANR', NULL, true),
    ('DE-42329', 'Wuppertal', 'DEHAM', NULL, true),
    ('DE-42329', 'Wuppertal', 'DUS', NULL, true),
    ('DE-42329', 'Wuppertal', 'FRA', NULL, true),
    ('DE-85774', 'Unterföhring', 'MUC', NULL, true),
    ('ES-07608', 'ES PIL-LARI, ISLAS BALEARES', 'MAD', NULL, true),
    ('ES-07608', 'ES PIL-LARI, ISLAS BALEARES', 'PMI', NULL, true),
    ('ES-08292', 'ESPARREGUERA', 'BCN', NULL, true),
    ('ES-28880', 'MECO, MADRID', 'MAD', NULL, true),
    ('ES-29620', 'TORREMOLINOS, MALAGA', 'MAD', NULL, true),
    ('FR-ARA-01150', 'Saint-Vulbas', 'BEANR', NULL, true),
    ('FR-ARA-01150', 'Saint-Vulbas', 'CDG', NULL, true),
    ('FR-ARA-01150', 'Saint-Vulbas', 'FRFOS', NULL, true),
    ('FR-BFC-89107', 'Sens', 'CDG', NULL, true),
    ('FR-BFC-89107', 'Sens', 'FRLEH', NULL, true),
    ('HK-HKG-002', 'Hong Kong Island', 'HKG', NULL, true),
    ('HK-HKG-002', 'Hong Kong Island', 'HKHKG', NULL, true),
    ('HK-HKG-003', 'New Territory', 'HKG', NULL, true),
    ('HK-HKG-003', 'New Territory', 'HKHKG', NULL, true),
    ('ID-31', 'SURABAYA', 'IDSUB', NULL, true),
    ('ID-338', 'SITUBONDO', 'IDSUB', NULL, true),
    ('ID-60183', 'ASEMROWO', 'IDSUB', NULL, true),
    ('ID-JKT-0001', 'NORTH JAKARTA CITY', 'IDJKT', NULL, true),
    ('IN-221401', 'Bhadohi', 'INTKD6', NULL, true),
    ('IN-247001', 'Saharanpur', 'INTKD6', NULL, true),
    ('IN-302003', 'JAIPUR', 'DEL', NULL, true),
    ('IN-302003', 'JAIPUR', 'INTKD6', NULL, true),
    ('IN-533005', 'Kakinada', 'HYD', NULL, true),
    ('IN-GJ-07', 'Kheda (Kaira)', 'INAMD', NULL, true),
    ('IN-KA-560', 'Bangalore', 'INWFD6', NULL, true),
    ('IT-00159', 'Rome', 'FCO', NULL, true),
    ('IT-20099', 'Sesto San Giovanni', 'ITGOA', NULL, true),
    ('IT-21054', 'Fagnano Olona', 'MXP', NULL, true),
    ('IT-42018', 'San Martino in Rio', 'ITGOA', NULL, true),
    ('IT-42018', 'San Martino in Rio', 'MXP', NULL, true),
    ('IT-45-001', 'Ravenna, Emilia-Romagna', 'ITGOA', NULL, true),
    ('JP-160', 'Shinjuku City, Tokyo', 'JPTYO', NULL, true),
    ('JP-173', 'Itabashi City', 'NRT', NULL, true),
    ('JP-311', 'Tsukuba, Ibaraki', 'JPTYO', NULL, true),
    ('JP-370', 'Takasaki, Gunma', 'NRT', NULL, true),
    ('JP-616-8312', 'Saganoshimizucho, Ukyo Ward, Kyoto', 'JPOSA', NULL, true),
    ('KH-PNH-000', 'Phnom Penh', 'PNH', NULL, true),
    ('KR-INC-001', 'Bupyeong', 'KRPUS', NULL, true),
    ('KR-INC-002', 'Gyeonggi-do', 'ICN', NULL, true),
    ('KR-INC-002', 'Gyeonggi-do', 'KRPUS', NULL, true),
    ('KR-PUS-000', 'Busan', 'ICN', NULL, true),
    ('KR-PUS-000', 'Busan', 'KRPUS', NULL, true),
    ('KR-SEL-05609', 'Songpa-gu, Seoul', 'KRPUS', NULL, true),
    ('MN-210', 'Ulan Bator', 'UBN', NULL, true),
    ('MO-0001', 'Macau Island', 'MFM', NULL, true),
    ('MO-0001', 'Macau Island', 'MOMFM', NULL, true),
    ('MY-JHR-000', 'Johor', 'MYPKG', 'MY-JHR', true),
    ('MY-JHR-030', 'Masai', 'KUL', 'MY-JHR', true),
    ('MY-KUL-000-A', 'wilayah persekutuan kuala lumpur', 'KUL', 'MY-KUL', true),
    ('MY-KUL-000-A', 'wilayah persekutuan kuala lumpur', 'MYPKG', 'MY-KUL', true),
    ('MY-KUL-099', 'Cheras', 'MYPKG', 'MY-KUL', true),
    ('MY-KUL-GOMBAK', 'Gombak', 'KUL', 'MY-KUL', true),
    ('MY-KUL-GOMBAK', 'Gombak', 'MYPKG', 'MY-KUL', true),
    ('MY-KUL-SETAPAK', 'SETAPAK', 'KUL', 'MY-KUL', true),
    ('MY-LBU-001', 'Rancha Rancha Industrial Estate, Labuan', 'LBU', 'MY-LBN', true),
    ('MY-LBU-002', 'Jalan Arsat', 'MYLBU', 'MY-LBN', true),
    ('MY-SBH-012', 'Beaufort', 'MYBKI', 'MY-SBH', true),
    ('MY-SBH-89850', 'Sipitang', 'MYBKI', 'MY-SBH', true),
    ('MY-SBH-91000', 'Tawau', 'MYTWU', 'MY-SBH', true),
    ('MY-SEL-064', 'Ampang Jaya, Selangor', 'MYPKG', 'MY-SGR', true),
    ('MY-SWK-002', 'Bintawa Industrial Estate', 'MYKCH', 'MY-SWK', true),
    ('MY-SWK-93010', 'Muara Tebas', 'MYKCH', 'MY-SWK', true),
    ('MY-SWK-93350', 'Tabuan Jaya', 'KCH', 'MY-SWK', true),
    ('MY-SWK-93350', 'Tabuan Jaya', 'MYKCH', 'MY-SWK', true),
    ('MY-SWK-94300', 'Kota Samarahan', 'MYKCH', 'MY-SWK', true),
    ('MY-SWK-98000', 'PERMYJAYA TECHNOLOGY PARK', 'MYMYY', 'MY-SWK', true),
    ('MY-SWK-98850', 'Lawas', 'MYBKI', 'MY-SBH', true),
    ('NL-0050', 'Groningen, Netherlands', 'AMS', NULL, true),
    ('NZ-0001', 'HUNTINGDON', 'NZLYT', NULL, true),
    ('PL-05092', 'Lomianki', 'WAW', NULL, true),
    ('PL-80209', 'Dobrzewino', 'GDN', NULL, true),
    ('PT-4590-049', 'Carvalhosa', 'OPO', NULL, true),
    ('PT-4590-049', 'Carvalhosa', 'PTLEI', NULL, true),
    ('PT-4750-823', 'Barcelos, Portugal', 'OPO', NULL, true),
    ('PT-4750-823', 'Barcelos, Portugal', 'PTLEI', NULL, true),
    ('SG-SIN-002', 'Changi', 'SGSIN', NULL, true),
    ('SG-SIN-347730', 'Tannery Road', 'SIN', NULL, true),
    ('SG-SIN-69201', 'Jurong East', 'SGSIN', NULL, true),
    ('SG-SIN-69201', 'Jurong East', 'SIN', NULL, true),
    ('SI-1330', 'KOCEVJE', 'LJU', NULL, true),
    ('SI-1330', 'KOCEVJE', 'SIKOP', NULL, true),
    ('TH-13', 'Pathum Thani', 'THBKK', NULL, true),
    ('TH-BKK', 'BANGKOK', 'BKK', NULL, true),
    ('TH-BKK-10250', 'SUAN LUAND DISTRICT, BANGKOK', 'BKK', NULL, true),
    ('TH-BKK-10250', 'SUAN LUAND DISTRICT, BANGKOK', 'THBKK', NULL, true),
    ('TH-BKK-10400', 'Dindeang District', 'THBKK', NULL, true),
    ('TN-8080', 'Menzel Temime', 'TUN', NULL, true),
    ('TW-HSZ-300', 'Hsinchu', 'TWKHH', NULL, true),
    ('TW-NWT', 'New Taipei City', 'TPE', NULL, true),
    ('TW-NWT-251', 'Tamsui District, New Taipei City', 'TPE', NULL, true),
    ('UK-B24', 'Erdington, Birmingham', 'GBLGP', NULL, true),
    ('UK-D7', 'Stourbridge', 'GBLGP', NULL, true),
    ('US-IN-001', 'Elkhart', 'USCHI', NULL, true),
    ('US-LA-70123', 'Harahan', 'IAH', NULL, true),
    ('US-OH-45066', 'Springboro, Ohio. 45066', 'USCHI', NULL, true),
    ('US-OH-45414', 'Dayton, Ohio', 'ORD', NULL, true),
    ('US-TX-78557', 'Hidalgo, TX', 'USHOU', NULL, true),
    ('VN-013', 'Quảng Ninh', 'VNHPH', NULL, true),
    ('VN-024', 'Hanoi City, Vietnam', 'VNHPH', NULL, true),
    ('VN-028-00001', 'District 11, Ho Chih Minh City', 'VNSGN', NULL, true)
ON CONFLICT (area_code, port_un_code) DO NOTHING;

-- Total: 153 rows
